### ISSUE TITLE
Routing

### ISSUE THREAD

**Issue by obisims** [basil2style/google-sheet-addon-svelte-starter#1]
Any thoughts how to best handle the routing for multi-page setups?

currently i'm containing it all in a single page with a reactive element that switches out components acting as pages but hit errors with svelte trying to destroy child elements that no longer exist when switching to another page.

~nice repo btw, good base

**Comment by basil2style** [comment]
@obisims For page routing, `svelte-spa-router` is good and simple. For the second GS page, you can add a new HTML file in the src. I'll update this repo with those .

**Comment by basil2style** [comment]
@obisims Updated the repo with the in-page navigation using svelte-spa-router & multi addon template page setup using vite build config
